from dataclasses import dataclass
from datetime import date
from typing import Literal

WORK_INTERVAL_MINUTES = 25
SHORT_BREAK_MINUTES = 5
LONG_BREAK_MINUTES = 15
INTERVALS_BEFORE_LONG_BREAK = 4


# Basically a Luau table with defined structure and constructor generated by Python
@dataclass
class Task:
    id: int
    title: str  # What is needed to do
    due: date  # Deadline of task
    remaining: int  # How long it would take to finish (estimated)
    confidence: int  # Confidence level from 1 - 5 regarding task


@dataclass
class ScheduleBlock:
    kind: Literal["study", "break"]
    task_id: int | None
    title: str
    minutes: int
    explanation: str


def task_priority(task: Task) -> tuple[date, int, int]:
    return (task.due, task.confidence, task.id)


def prioritize_tasks(tasks: list[Task]) -> list[Task]:
    unfinished_tasks = [task for task in tasks if task.remaining > 0]
    return sorted(unfinished_tasks, key=task_priority)


def allocate_plan(
    tasks: list[Task], today_date: date, available_minutes: int
) -> list[ScheduleBlock]:
    prioritized_tasks = prioritize_tasks(tasks)
    result: list[ScheduleBlock] = []

    time_left = available_minutes
    interval_remaining = WORK_INTERVAL_MINUTES
    completed_intervals = 0

    for task in prioritized_tasks:
        if time_left <= 0:
            break

        task_remaining = task.remaining

        while task_remaining > 0 and time_left > 0:
            # Insert a break only when more work will follow it.
            if interval_remaining == 0:
                is_long_break = completed_intervals % INTERVALS_BEFORE_LONG_BREAK == 0
                break_minutes = (
                    LONG_BREAK_MINUTES if is_long_break else SHORT_BREAK_MINUTES
                )

                # A break must leave room for at least one minute of work.
                if time_left <= break_minutes:
                    return result

                result.append(
                    ScheduleBlock(
                        kind="break",
                        task_id=None,
                        title="Long break" if is_long_break else "Short break",
                        minutes=break_minutes,
                        explanation=(
                            "Four work intervals completed."
                            if is_long_break
                            else "One work interval completed."
                        ),
                    )
                )

                time_left -= break_minutes
                interval_remaining = WORK_INTERVAL_MINUTES

            block_duration = min(
                interval_remaining,
                task_remaining,
                time_left,
            )

            result.append(
                ScheduleBlock(
                    kind="study",
                    task_id=task.id,
                    title=task.title,
                    minutes=block_duration,
                    explanation=(
                        f"Due {task.due}; confidence {task.confidence}/5. "
                        "Scheduled by earliest deadline, then lower confidence."
                    ),
                )
            )

            task_remaining -= block_duration
            time_left -= block_duration
            interval_remaining -= block_duration

            if interval_remaining == 0:
                completed_intervals += 1

    return result
